### ISSUE TITLE
UI: Add separate lists or xml files for RegistrationRequests

### ISSUE THREAD

**Issue by Columbium41** [uOttawaSEGA2023/Medihub#33]
## Tasks
- [ ] Create separate lists or xml layouts for pending, declined, and approved registration requests

## Logic
- For pending requests, show the card with the authorize and deny buttons (already done, see screenshot)
- [ ] For declined requests, show the card with the authorize button only
- [ ] For approved requests, show no buttons

#### Pending Request Screenshot:
![Screenshot 2023-10-27 at 5 20 47 PM](https://github.com/uOttawaSEGA2023/project-project-group-24/assets/75919484/d9a3fa13-3149-42ba-a918-9f2481f0dcbd)
